### ISSUE TITLE
shadow-cljs suggestions

### ISSUE THREAD

**Issue by thheller** [maxlorenz/vscode-cljs-extension#1]
Cool stuff. I have a few suggestions though.

> (Read: Shadow-cljs as in no Java at all)

This is incorrect, `shadow-cljs` uses the normal JVM compiler so you definitely need Java.

This `shadow-cljs.edn` should be enough. 

```clojure
{:dependencies []

 :source-paths ["src/cljs"]

 :builds
 {:extension
  {:target :node-library
   :exports {:activate cljs-ext.core/activate}
   :output-to "extension.js"}}}
```

- `:optimizations` defaults to `:simple` for `release` and `:none` for development.
- `:output-wrapper` is always done for `:node-library`, the config option has no effect.

If you'd drop `lein` support you could do this for `src/cljs/cljs_ext/core.cljs`

```clojure
(ns cljs-ext.core
  "VSCode extension in ClojureScript"
  (:require ["vscode" :as vscode :refer (commands window)]))
  
(defn say-hello-command []
  (.showInformationMessage window "hello world"))

(defn activate [context]
  (.registerCommand commands "extension.sayHello" say-hello-command)
  (.log js/console "Extension activated."))
```

The `:require` syntax is only supported by `shadow-cljs` (see [CLJS-2061](https://dev.clojure.org/jira/browse/CLJS-2061) for official progress).

I also recommend `npm install --save-dev shadow-cljs` in the project so it gets picked over the global install and can be updated with the project.

**Comment by maxlorenz** [comment]
Thanks for the suggestions! I really like removing lein support as the code gets a lot cleaner now. I'll watch CLJS-2061. Much appreciated!

**Comment by thheller** [comment]
In case you are interested, I built a plugin myself a while ago that also did live reloading.

```clojure
(ns demo.plugin
  (:require ["vscode" :as vscode]))

(defonce context-ref
  (volatile! nil))

(defonce disposables-ref
  (volatile! []))

(defn say-hello []
  (.. vscode -window (showInformationMessage "hello world")))

(def commands
  {::say-hello say-hello})
 
(defn stop []
  (doseq [x @disposables-ref]
    (.dispose x)))

(defn disposable [x]
  (.. @context-ref -subscriptions (push x))
  (vswap! disposables-ref conj x))

(defn start []
  (doseq [[id cmd-fn] commands]
    (disposable (.. vscode -commands (registerCommand (-> id str (subs 1)) cmd-fn)))))

(defn activate [context]
  (vreset! context-ref context)
  (start))

(defn deactivate []
  (stop)
  ;; code wants a promise or undefined
  js/undefined)
```

and configured via `:devtools` on the `:builds` config.

```clojure
:devtools
{:before-load demo.plugin/stop
 :after-load demo.plugin/start}}
```

I'm not sure how reliable this will be for actual plugins but it worked for the `vscode-languageclient` prototype I did for CLJS. `stop` will be called before reloading any code and `start` when done, re-using the disposable feature from VSCode to properly remove all old references. Not sure you always need to do that.

**Comment by maxlorenz** [comment]
Thanks, I'll look into that
